### PR TITLE
Hallo ich will auch ein Stück vom Kuchen 

### PR DESCRIPTION
**Pull request by JayReturns**

### CODE REVIEW

**Review by AlexSchmitz222 — CHANGES_REQUESTED** [review]
Hello,

Surely, we'd like to honour your contributions.
Please submit a detailed list of contributions, added features, added parts and timestamps.

Many thanks,
Meee

**Comment by JayReturns** [comment]
No. You should be able get the gist vy by studying my changes. 

Sincerely
Jay

**Comment by JayReturns** [comment]
:(

**Comment by JayReturns** [comment]
hehe

**Comment by AlexSchmitz222** [comment]
@JayReturns Look [here](https://github.com/AlexSchmitz222/DCC-Decoder/blob/main/THT%20Components/Schaltplan%20V1.0.brd)

**Pull request closed without merging**
